formio/formio

package.json
Without it, src/db/updates/2.2.0.js fails to run.
=> "event-chain" module declaration is missing

config/default.json, index.js, package.json, src/actions/AuthAction.js, src/actions/DefaultAction.js, src/actions/OAuthAction.js, src/actions/actions.js, src/authentication/index.js, src/middleware/submissionHandler.js, src/oauth/facebook.js, src/oauth/github.js, src/oauth/oauth.js, src/util/hook.js, src/util/oauth.js, src/util/util.js, test/actions.js, test/auth.js, test/bootstrap.js, test/config.json, test/form.js, test/nested.js, test/oauth.js, test/resource.js, test/roles.js, test/submission.js, test/test.js
Also:
- Added tests for OAuth
- Added filtering queries to /form/:formId/components endpoint (though ultimately unused by OAuthAction)
- Added tests for filtering queries
- Made DefaultAction honor priority instead of always running first
- Fixed jwt deprecation warning
- Fixed hooks crashing with empty config
=> FA-416 Added OAuthAction

package.json, src/actions/OAuthAction.js, src/actions/actions.js, src/authentication/index.js, src/models/Submission.js, src/oauth/facebook.js, src/oauth/github.js, src/oauth/oauth.js, src/oauth/office365.js, src/resources/SubmissionResource.js, src/util/oauth.js, src/util/util.js, test/config.json, test/oauth.js, test/oauth/facebook.js, test/oauth/github.js, test/oauth/office365.js
- Office 365 is now an option for OAuth authentication
- Tokens obtained from OAuth authentication are now stored in the `externalTokens` field of a Submission. This is not returned via API, however
- Some refactoring to accomodate Office 365's different OAuth approaches.
- Added mechanism to retrieve a user's token and attempt to refresh it if necessary (`formio.oauth.getUserToken()`)
- Added more tests for testing individual oauth providers
- Added tests to check externalTokens
=> FA-489 Added Office 365 OAuth + Storing OAuth tokens in submissions

.eslintrc, package.json
For now, run eslint with `npm run lint`. Should later be added to the npm test script when we have lint errors under control.
=> Added eslint-config-formio to .eslintrc

src/templates/import.js, test/template.js, test/test.js
Defer replacing resource component ids until all resources are created, so nested dependencies don't crash the import.
=> FA-620 Fix nested resources crashing on import

src/actions/actions.js, test/actions.js
The Does Not Equal setting on conditional actions was broken in commit d357f7a where an === was changed to &&. This fixes it and creates tests.
=> Fix not equal conditional actions

src/actions/fields/signature.js, test/submission.js
=> Coerse null signatures into empty strings to keep bad errors from being thrown.

install.js
fixed #365 
Email validation for username based on w3c input type email regex (https://www.w3.org/TR/2012/WD-html-markup-20120320/input.email.html)
=> Validate email on first installation

package.json
In package.json there is:
```
"engines": {
"node": ">=6.0.0"
},
```
But npm didnt force the node version, is just declarative.
So I added check-node-version to force it to use node >= 6.0.0
=> Force node check version

src/actions/fields/form.js, src/actions/fields/index.js, src/middleware/submissionHandler.js
In multi-form workflows it can be useful to be able to navigate from a child form component's submission to the parent's submission.
Set an externalId of type _parent_ in the children back up to the parent.
=> Set child form parent

src/actions/SQLAction.js
My form has a SQL Query action titled 'SQL Select'.
It runs the query _select name, age from flintstones where id = '{{ data.id }}'_ on Microsoft SQL Server.
The action executes After Read.
Would like to be able to access the query results in Calculated Value scripts of Name and Age components.
Code change returns results of SQL Server get query in submission's metadata.
So Calculated Value scripts can access query results with code like _value = submission.metadata['SQL Select'].rows[0][0];_
=> Return SQL Server query results from get action

src/db/index.js
I think the original intent of the db updates was to allow patch differences between the codebase. Apparently we never implemented allowing patch differences.
=> Allow patch version differences in db schema.

src/actions/SQLAction.js
`mssql.connect` call is crashing server with error `Error: Global connection already exists. Call sql.close() first.`
Changed to use connection pool to connect.
Format of result object has changed in mssql 4.1.0.
Changed to use result object's recordset.
=> Adjust SQL action for breaking changes in mssql 4.1.0

src/models/Schema.js, src/models/models.js
By making "schema" a first class model we will be able to use the built in tools to read and write other values to the schema collection.
=> Make schema model a first class model.

install.js
It would be helpful to be able to automate the install of form.io - this is a first pass at doing that (doesn't have docs, tests etc).
To use this first `export UNATTENDED_INSTALL=1` to skip the interactive prompts. Then you will want to create a config/custom-environment-variables.json file that specifies mapping of environment variables to config overrides - e.g.:
```
{
"domain": "DOMAIN",
"basePath": "",
"mongo": "MONGO",
"mongoSecret": "MONGOSECRET",
"jwt": {
"secret": "JWTSECRET"
}
}
```
Then, export values for each of those variables and start the install.
=> Enable unattended install driven by environment variables.

README.md
Since `docker-compose.yml` mounts the local directory as a volume for the `formio` container, and the `Dockerfile` does not execute `npm install` when building the image, it is necessary to run `npm install` to make the required node modules available before attempting to start the containers.
Fixes https://github.com/formio/formio/issues/772.
=> Add npm install step to README

Dockerfile
2.7.15-r3 is no longer available, so building an image from this Dockerfile fails when trying to add it.
Fixes #783
=> Use python version 2.7.16-r1 in Dockerfile

config/default.json, server.js
There were some problems with CORS headers. This commit should fix them.
Added a config in default.json "allowedOrigins". This array should contain the client app URL(s) allowed to access the application.
Also fixes the OPTIONS method request mentioned in #672
=> CORS: access control allow origin header added

src/middleware/accessHandler.js, test/form.js
Introduced user access retrieval as first step.
Forms are only returned if their configured `read_all` access roles overlap with the roles of the requesting user.
If project-level access denies `read_all` to the user, an empty result set is returned.
Refactored to replace nested callbacks with async/await.
=> Limit /access return data by project and form read access

src/util/util.js
#799 changed the behavior of the File component during `GET /.../submission` index queries to match the behavior of the Signature component: returning `"YES"` or `""` based on whether data exists. Submission-level queries were (and are) unaffected; they return the full file record.
This changes the behavior to be a fair bit nicer: it returns everything except the file's URL, and only in those cases where it is a data-URL.
=> [FOR-2492] Nicer response behavior for file component submission index endpoint

src/resources/Validator.js
Hi guys, I want to add a minItems and maxItems mainly to validate attachments. What do you think of adding this change?
Is this the right place to PR so the code gets into this image later https://cloud.docker.com/u/formio/repository/docker/formio/formio-enterprise ?
```js
{
"autofocus": false,
"input": true,
"tableView": true,
"label": "Test min-max",
"key": "page1TestminMax",
"image": true,
"imageSize": "200",
"placeholder": "",
"multiple": true,
"defaultValue": "",
"protected": false,
"persistent": true,
"hidden": false,
"filePattern": "*",
"fileMinSize": "0KB",
"fileMaxSize": "1GB",
"type": "file",
"storage": "s3",
"slides": true,
"labelPosition": "top",
"tags": [],
"conditional": {
"show": "",
"when": null,
"eq": ""
},
"weight": 0,
"properties": {},
"validate": {
**"minItems": 1,** …
```
=> Add minItems and maxItems validation

index.js, src/db/index.js, src/models/Form.js, src/models/Role.js, src/models/Token.js
Fixes the three Mongoose deprecation warnings on startup:
- added `useUnifiedTopology: true` to connection options
- added `useCreateIndex: true` to connection options
- converted done-style async model validators to use promises, allowing us to remove the deprecated `isAsync: true` flag on associated fields
=> Fix Mongoose deprecation warnings

install.js
During installation, the client is downloaded from Github repositories. `install.js` uses an outdated archive link `https://nodeload.github.com`, but Github now serves archives on `https://codeload.github.com`.
A better solution would be to ask the Github API for a link to the archives, as documented here: https://developer.github.com/v3/repos/contents/#get-archive-link
This fixes #583.
=> Fix URL to download Github archives

src/export/export.js
Temp token generated using the x-admin-key header returns a temp token without user.  The export endpoint fails with status code 400 if no user id is set int he token.  This fixes the token validation check so that it accepts temp tokens generated with the admin key.
=> fixed temp token check generated with admin key

Dockerfile
Hi,
I noticed the tag `node:lts-alpine` has been updated and now points to 3.11, this causes the build to fail since the version of python2.7 and g++ have changed.
```
...
Step 3/11 : RUN apk update &&     apk upgrade &&     apk add python=2.7.16-r1 &&     apk add make=4.2.1-r2 &&     apk add g++=8.3.0-r0
---> Running in c72802b5a194
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz
v3.11.2-31-g433facdd60 [http://dl-cdn.alpinelinux.org/alpine/v3.11/main]
v3.11.2-32-g587f005260 [http://dl-cdn.alpinelinux.org/alpine/v3.11/community]
OK: 11261 distinct packages available
(1/2) Upgrading libcrypto1.1 (1.1.1d-r2 -> 1.1.1d-r3)
(2/2) Upgrading libssl1.1 (1.1.1d-r2 -> 1.1.1d-r3)
OK: 7 MiB …
```
=> Pin version of base docker image, use node:lts-alpine3.10

src/export/exporters/CSVExporter.js
This is a small fix in the CSV exporter.  Added `editgrid` component to ignore list as we only want the components row data.
Fixes the edit grid portion in issue https://github.com/formio/formio/issues/980
=> Added editgrid to CSV exporter ignore list

src/middleware/permissionHandler.js
I'm not quite sure that this is correct. 
----------------------
Basically if I don't use formio-server 'getSchema' hook ( https://github.com/formio/formio-server/pull/705/commits/787ed12ae67ae1ec3bdbc11acf9d4ce1cc73ab08 ) returns undefined and if I do use formio-server it returns schema version. 
P.S. I'll create the same PR against master if that one is ok.
=> 112 split roles fixed bug with reverse compatibility

src/cache/cache.js, src/templates/import.js
The property which specifies the revision number for Nested Forms was changed within the builder from 'formRevision' to 'revision'
=> FIO-1140: Fixes an issue where deprecated formRevision property is added when deploying a version to a stage

Dockerfile
I had trouble with the Docker build.  It looks like a couple weeks ago someone changed `formio.js`'s package.json file to load `text-mask` from a git path.  Since `git` isn't part of the `alpine` Docker container this container's build fails.
=> fix: allow Docker to load git npm paths

index.js, package.json, src/actions/SaveSubmission.js, src/actions/actions.js, src/util/util.js
- Replaced cloneDeep to freeze for VM to increase speed and decrease memory usage.
- Added a GC force middleware to prevent out-of-memory error.
Related PR https://github.com/formio/formio-server/pull/847
=> FIO-3223: Fixes an error with out of memory

src/actions/WebhookAction.js
After accidentally blocking myself while testing the webhook action in the admin login form, I thought it should be a good idea to show users what actually checking an unknown checkbox do.
=> Unhid block component label in webhook action settings form

index.js
Seems like there is some kind of incompatibility between Mongoose and MongoDB driver. While the latest versions of MongoDB driver are using file path to read ssl certificates, Mongoose requires the contents of the certificate. This path fixes code working with Mongoose to use the contents of the certificate.
=> Quick fix to point the issue

src/db/index.js
Added small random delay to database setup process to prevent possible race conditions during setup
When multiple copies of the api server are spawned simultaneously to deal with load, there is a possibility that both will attempt to perform database upgrades at the same time, inserting multiple locks into the schema collection
=> boot race conditions

Changelog.md
The Changelog file had a origin/master which might have been caused due to a merge conflict
=> 📚 remove origin/master from CHANGELOG

index.js, src/middleware/alias.js, src/middleware/configHandler.js, src/middleware/middleware.js
In order to allow extra compatibility with the enterprise server, I have added the public configuration endpoint.
The public configuration can be added through the `config/default.json` file under the `public` key:
```json
{
...
"public": {
"foo": "bar"
}
}
```
The public configuration can also be defined through environment variable under the key `PUBLIC_CONFIG` using a JSON string.
```bash
export PUBLIC_CONFIG='{"foo":"bar"}'
npm start
```
=> Added public config support

src/actions/EmailAction.js, src/util/email.js
Previously, it was possible for the PDF server to return a non-200 response (or for the download PDF middleware to throw an error) during the PDF submission attachment process in the email action and for this response to get bundled as base64 and attached to the resulting email. This PR replaces this behavior by passing a potential setActionItemMessage method (which defaults to a noop for open source) down the callback chain so it is accessible during the PDF attachment process.
=> FIO-5911: update email action steps

src/templates/export.js
Under certain circumstances - namely a project with a nested form that includes a revision pointed at a form with revisions disabled - exporting a project template would crash the server. This PR fixes that behavior by adding nullish checks to forms, components, and revisions during the export process.
=> FIO 6579: Fix project template exports crashing the server

src/actions/properties/reference.js, src/middleware/filterMongooseExists.js, test/submission.js
https://formio.atlassian.net/browse/FIO-4216
https://formio.atlassian.net/browse/FIO-6601
Previously, only default 'submissions' db collection was checked when getting all form submissions and value is a reference. With this changes the name for db collection is composed from project name and form settings 'collection' config.
This felt the normal way to do this.
None
I added automated tests + manually
=> FIO-4216 | FIO-6601 - Fixes no custom submission collection lookup when getting submissions

test/submission.js
I wrote a test in OSS formio that dealt with custom submission collections. Since the test suite runs with a hosted license, I added a check for config.hosted for that particular test
=> fix submission collections tests failing on hosted env

src/authentication/index.js, src/db/index.js, src/db/updates/3.1.5.js
https://formio.atlassian.net/browse/FIO-6840
Long running `$regex` queries were appearing in our hosted production environment, sometimes taking as long as 10-12 seconds even when there is an index. It turns out that [case insensitive `$regex` queries cannot utilize indexes](https://www.mongodb.com/docs/manual/reference/operator/query/regex/#index-use), so this PR 
* adds a case-insensitive index for the `data.email` property; and
* changes the authentication method to attempt to utilize a collation-aware (i.e. case-insensitive) query before falling back to a $regex query.
With this change, OSS formio's authentication process should be a lot more performant.
Since this PR adds a schema update and a collation-aware …
=> FIO-6840: Refactor authentication to use case-insensitive query and fallback to $regex

src/actions/properties/reference.js, src/middleware/filterMongooseExists.js
Reverts formio/formio#1592
Related Jira ticket:
https://formio.atlassian.net/browse/FIO-6924
This PR seems to be causing tests to fail.
Also reverting dependent PR https://github.com/formio/formio-server/pull/1294 with https://github.com/formio/formio-server/pull/1302.
=> Revert "FIO-4216 | FIO-6601 - Fixes no custom submission collection lookup when getting submissions"

src/actions/properties/reference.js, src/middleware/filterMongooseExists.js
https://formio.atlassian.net/browse/FIO-4216
https://formio.atlassian.net/browse/FIO-6601
Previously, only default 'submissions' db collection was checked when getting all form submissions and value is a reference. With this changes the name for db collection is composed from project name and form settings 'collection' config.
This felt the normal way to do this.
[formio-server:1294](https://github.com/formio/formio-server/pull/1294)
I added automated tests + manually
=> FIO-6601: Fixes no custom submission collection lookup when getting submissions

src/export/exporters/CSVExporter.js, test/export/CSVExporter/CSVExporter.js, test/fixtures/forms/azureAddressComponent.js, test/fixtures/forms/googleAddressComponent.js, test/fixtures/forms/nominatimAddressComponent.js
https://formio.atlassian.net/browse/FIO-6966
Previously, address component data mapping was outdated and address component data in CSV appeared empty.
This seemed to be the right spot to fix address component data mapping for CSV submissions export.
None
I've added automated tests to cover OpenStreetMap, Azure Maps and Google Maps cases
=> FIO-6966: Fixes empty address component data in CSV

src/util/email.js
n/a
Our production servers began thrashing 9/14/23 with the message 
```
Uncaught exception:
current-api-server-1  | [UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "Invalid response.".] {
current-api-server-1  |   code: 'ERR_UNHANDLED_REJECTION'
current-api-server-1  | }
current-api-server-1  | UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "Invalid response.".
```
Although the error lacks a descriptive call stack, I believe this is due to the email …
=> bugfix: add catch block to nunjucks injection

src/actions/actions.js, src/util/conditionOperators/ConditionOperator.js, src/util/conditionOperators/DateGreaterThan.js, src/util/conditionOperators/DateGreaterThanOrEqual.js, src/util/conditionOperators/DateLessThan.js, src/util/conditionOperators/DateLessThanOrEqual.js, src/util/conditionOperators/EndsWith.js, src/util/conditionOperators/GreaterThan.js, src/util/conditionOperators/GreaterThanOrEqual.js, src/util/conditionOperators/Includes.js, src/util/conditionOperators/IsDateEqual.js, src/util/conditionOperators/IsEmptyValue.js, src/util/conditionOperators/IsEqualTo.js, src/util/conditionOperators/IsNotDateEqual.js, src/util/conditionOperators/IsNotEmptyValue.js, src/util/conditionOperators/IsNotEqualTo.js, src/util/conditionOperators/LessThan.js, src/util/conditionOperators/LessThanOrEqual.js, src/util/conditionOperators/NotIncludes.js, src/util/conditionOperators/StartsWith.js, src/util/conditionOperators/index.js, test/actions.js
Reverts formio/formio#1623 which reverted the formio/formio#1596. The following description is a copy/paste of formio/formio#1596
https://formio.atlassian.net/browse/FIO-6630
Previously, we had a form allowing to configure only 1 simple condition for executing form actions.
Now we have more complex form allowing to combine different conditions and using different operators 
The idea was taken from our expanded UI for components conditions/logic.
There is also a required PR for formio.js https://github.com/formio/formio.js/pull/5270
Manually for now, automated tests are coming :)
=> Re-implement - FIO-6630: Expanded Actions Logic UI

src/actions/actions.js, src/util/conditionOperators/index.js
https://formio.atlassian.net/browse/FIO-7235
Adds State, Created and Modified properties to the When select dropdown of expanded action conditions. That allows to configure actions based on when the submission was created/updated or on its state. 
Also now it try to get value from res.resource.item instead of req.body which won't have a submission data on most triggers except of After Create one. If there is no res.resource.item, it will fallback to the req.body. 
When user selects Created/Modified fields, the description of the select dropdown will be updated to warn user that those fields won't be persitent within a submission on some trigger types.
Since this Expanded Actions UI feature was moved to a later release, we need to merge it first cause this PR is an extension for that …
=> FIO-6630: Adds root level properties to action conditions

src/templates/export.js, src/templates/import.js, test/fixtures/templates/testDataTableWithResource.json, test/templates.js
https://formio.atlassian.net/browse/FIO-7491
Added logic that 
- replaces the DT resource id by machine name when exporting the template with resource DT 
- replaces the DT resource machine name with valid resource id when importing the template.
manually + tests added
=> FIO-7491: fixed an issue where dataTable component with resource data type does not work after exporting/importing

package.json
https://formio.atlassian.net/browse/FIO-7538
vm-utils was pulling directly from master. Changes were made to master that caused the tests to start failing. This PR puts vm-utils back to a version prior to the changes that were made in master.
=> FIO-7538: Change vm-utils link in package.json

src/actions/actions.js
https://formio.atlassian.net/browse/FIO-7330
Previously, action settings form fields with restricted access won't be hidden and sometimes changing them could make the server crush. This PR fixes hiding fields with restricted access.
[formio-server:1368](https://github.com/formio/formio-server/pull/1368)
I've added automated test
=> FIO-7330: fix bug of displaying settings for restricted fields

yarn.lock
Build errors with axios@  > 1.5.1.
This pins the version at 1.5.1 for now to get a build through while we investigate axios changes.
=> Revert axios to 1.5.1 from 1.6.x

src/actions/SaveSubmission.js, test/actions.js
https://formio.atlassian.net/browse/FIO-7330
Previously, endpoint to get action settings would crush if `actionSettingsForm` not found, this PR adds skip for the hook if it's not found.
None
I've added automated test
=> FIO-7330: Fixes action settings endpoint crushing

src/actions/properties/reference.js
https://formio.atlassian.net/browse/FIO-7514
When the subrequest for reference submission is made, the submissionId param of the main submission request overrides the reference subId and the submission subrequest returns the 404 error. This PR unsets submissionId param from subrequest to prevent this situation.
https://github.com/formio/formio.js/pull/5429
Manually
=> FIO-7514: fixed an issue where submission reference object is not attached to the value of select component with reference enabled

src/actions/EmailAction.js
https://formio.atlassian.net/browse/FIO-7623
Because we are calling next() to prevent blocking while sending emails, after the response is sent, req.params are cleared. We already was restoring them after emailer.getParams got resolved, but is some scenariouse, the response is not sent at that moment, so req.params are getting cleared after we restored them. So I adjusted this solution to restore req.params after the response is sent by using 'finish' event. 
*Use this …
=> FIO-7623: Fixes an issue where Email action with Logs turned on will fail for the nested form with Attach Submission PDF

src/export/export.js
https://formio.atlassian.net/browse/FIO-7498
Changed the way to pass the data to decrypt hook, so that if decrypt fails it should display hashed value instead of buffer array
=> FIO-7498 Changed the passing of a data field to decrypt hook

Dockerfile, README.md, docker-compose.yml
n/a
Previously our open source Dockerfile simply mounted the source directory as a read/write volume. As we've introduced additional dependencies that require a build step and result in arch-specific binaries, this approach is not sustainable. This PR modernizes the Dockerfile to build an image that is independent of the host machine.
n/a
locally
=> Modernize the Dockerfile to decouple from host machine

src/middleware/submissionHandler.js, src/resources/Validator.js, test/submission.js
https://formio.atlassian.net/browse/FIO-8047
Because Data Table components have an array data model, @formio/core's `filter` process will skip over their submission data with the expectation that their constituent components will be iterated over by eachComponentData. However, Data Table components that use the "Reference" data source populate their components at runtime, which means that the form component that the server has access to has only an empty array. This PR adds a method to the `Validator` class that is injected into the `dereference` processor to dereference the target Resource by accessing the database directly.
This can and should eventually be expanded to cover all dereferencing use cases such as save-as-reference submission objects or other components that lazily load …
=> FIO 8047: add dereference for datatable components

src/db/index.js
https://formio.atlassian.net/browse/FIO-7671
An enterprise customer was running into an error - "Unique and compound indexes do not support nested paths" - when creating submissions collections versus their CosmosDB installation. It seems that in certain CosmosDB deployments creating a compound index with a nested path (e.g. `createIndex({col1: 1, 'data.col1': 1})`) will cause an error to bubble to the client, whereas in other deployments (ours in particular) the operation will fail silently and the index will simply not be created. 
Although I'm still not sure of where the difference in these deployments lies - perhaps Microsoft does A/B feature testing on a subset of users? perhaps there's a deep beta-feature setting that is enabled by default on some deployments and not on others? - …
=> FIO 7671: nested paths cosmosdb feature test

src/models/Form.js
https://formio.atlassian.net/browse/FIO-7933
*Added PDF Document Designer for Webform PDF Output. The pdfComponents property has been added to the form schema, which are an array of components displayed on the PDF download page*
*https://github.com/formio/formio-app/pull/1551*
*https://github.com/formio/pdf-server/pull/332*
*https://github.com/formio/formio.js/pull/5539*
*https://github.com/formio/bootstrap/pull/89*
*manually with using pdf download*
=> FIO-7933 Added pdfComponents to Form schema

package.json, src/util/staticVmDependencies.js, yarn.lock
https://formio.atlassian.net/browse/FIO-8169
Use the resolve dependency (68MM weekly downloads) to resolve filepaths rather than require. This change isn't strictly necessary because this code isn't bundled by webpack as the Enterprise Server code is (see [formio-server#1468](https://github.com/formio/formio-server/pull/1468)) but I figure it'd be nice to keep it consistent.
n/a
n/a
=> FIO-8169: add resolve dep to mirror enterprise server

src/actions/SaveSubmission.js, src/actions/actions.js, src/util/util.js, test/config.json
https://formio.atlassian.net/browse/FIO-8171
Adds a configurable VM2 timeout
* [formio-workers#55](https://github.com/formio/formio-workers/pull/55)
I added automated tests to formio-server
=> FIO-8171: add configurable VM2 timeout to 3.4.x

test/fixtures/templates/selectWithResourceDataSrcAndDefaultValueNoResourcesExport.json, test/templates.js
https://formio.atlassian.net/browse/FIO-8137 & https://formio.atlassian.net/browse/FIO-8152
https://app.circleci.com/pipelines/github/formio/formio-server/5909/workflows/b4f34671-52df-49ae-ac45-69804f6355c2/jobs/27302
The issue was that the project templates utilized had different names. In `formio` we do not have the concept of project seperation so they'd get imported as the same template wihtout issue. When this test is done in formio-server they need to match up so that when imported they are seen as the same project template.
https://github.com/formio/formio/blob/0781c7f528d42b7f5cd81ceb56fef8ba18d86798/test/templates.js#L3809-L3824
This will allow tests to pass on `formio` and `formio-server`
n/a
n/a
Passes pipeline tests for …
=> FIO-8152: Check if Import Resource Exists in New Project for Select Component with Resource 

src/export/exporters/CSVExporter.js, test/export/CSVExporter/CSVExporter.js, test/fixtures/forms/azureAddressComponent.js, test/fixtures/forms/googleAddressComponent.js, test/fixtures/forms/nominatimAddressComponent.js
https://formio.atlassian.net/browse/FIO-6966
Address component data was not always present in csv submissions export, which this PR fixes.
None
I've updated automated tests, so to cover different address providers and manual input mode.
=> FIO-6966: Fixes missing address component data in csv exported submissions

src/actions/EmailAction.js, test/actions.js
https://formio.atlassian.net/browse/FIO-7299
Previously, if email action was configured with both 'before' and 'after' handlers, the message sent for the 'after' would be broken. This PR makes a fix for this issue.
Problem was with settings object reference kept the same, so I've made a clone of it for every new email being sent.
None
I've added a test for the failing scenario
=> FIO-7299: Fix email action with the 'before' handler issues

src/actions/fields/form.js, test/nested.js
https://formio.atlassian.net/browse/FIO-8150
When draft submissions of forms containing nested forms were POSTed to the server, the child form's `req.submission` object would be [merged with the parent](https://github.com/formio/formio/blob/f2c3c72e5c6506ae36a9a730f6f35acbfa25a8d1/src/middleware/submissionHandler.js#L221). This PR isolates the subrequest's `req.submission` object so that parent data does not leak into the child.
n/a
n/a
Added an automated test, formio-server tests pass when linked
=> FIO-8150: pin subform submission object

src/actions/SaveSubmission.js, src/middleware/submissionHandler.js, test/actions.js, test/fixtures/forms/testMappingDataForm.js
https://formio.atlassian.net/browse/FIO-8428
Submission data transformation was working not right because of misconfiguration of @formio/vm evaluator, this PR adjusts the options so that data is getting transformed correctly.
I've added automated tests that verify data is submitted to configured resource and it's transformed as defined in save submission action settings.
=> FIO-8428: Fixes save submission action data transformation

src/actions/actions.js
https://formio.atlassian.net/browse/FIO-8903
Originally, the fieldset component is a layout component that does not have its own value. Tree property is applicable only for data components. So, tree property inside fieldset causes the data path to be calculated incorrectly  and, consequently, the validation is skipped for components inside.
Manually
=> FIO-8903: fixed an issue where actions can be saved without required fields

src/util/conditionOperators/IsEqualTo.js, test/actions.js
https://formio.atlassian.net/browse/FIO-8849
Added a specific check for select boxes in isEqual operator
https://github.com/formio/formio.js/pull/5767
Manually + tests
=> FIO-8849: fixed an issue where isEqual operator doenot work for condition based on selectboxes

src/util/conditionOperators/index.js
https://formio.atlassian.net/browse/FIO-8860
https://formio.atlassian.net/browse/FIO-8874
https://formio.atlassian.net/browse/FIO-8861
Removed input mask from the condition value field as it does not allow to add a partial  value and, consequently, the operators like includes, startsWith and some other are not applicable.
Manually
https://github.com/formio/formio.js/pull/5764
https://github.com/formio/premium/pull/323
=> FIO-8860-8861-8874: fixed an issue where it is impossible to add value for condition operators for time and phone number

src/util/conditionOperators/DateGreaterThan.js, test/actions.js
https://formio.atlassian.net/browse/FIO-8798
Incomplete date formats have been added to the getValidationFormat function for date validation (MM-YYYY, DD-MM etc.) Also added functionality that allows you to set the date format during validation only for the day component. The changes allow to correctly perform comparison of not full dates during the execution of actions.
https://github.com/formio/core/pull/140
https://github.com/formio/formio.js/pull/5760
auto tests
=> FIO-8798: added validation of not full dates

src/util/conditionOperators/IsEmptyValue.js, src/util/conditionOperators/index.js
https://formio.atlassian.net/browse/FIO-8900
https://formio.atlassian.net/browse/FIO-8899
- fixed an issue where isEmpty operator always return false for address
- fixed an issue where address subcomponents display in available components options for action condition UI
https://github.com/formio/premium/pull/328
https://github.com/formio/formio.js/pull/5789
Manually
=> FIO-8900-8899: fixed address component in condtions UI and fixed an issue where isEmpty operator always return false for address

index.js, package.json, src/actions/SaveSubmission.js, src/actions/actions.js, src/middleware/submissionHandler.js, src/resources/Validator.js, test/validator.js, yarn.lock
https://formio.atlassian.net/browse/FIO-9064
A `getCustomDefaultValue` method was added to the InstanceShim class in @formio/vm, which required an ad-hoc evaluation of component JSON properties. To ensure that the timeout is able to be configured for all evaluations, the `configureVM` method was refactored to include a global timeout. This PR updates the downstream code to correspond to those changes made in [@formio/vm#35](https://github.com/formio/vm/pull/35).
n/a
* https://github.com/formio/vm/pull/35
n/a
=> FIO-9064: refactor timeout to be part of config rather than function arg

src/actions/SaveSubmission.js, src/actions/actions.js, src/middleware/submissionHandler.js, src/resources/Validator.js
https://formio.atlassian.net/browse/FIO-9064
A `getCustomDefaultValue` method was added to the InstanceShim class in @formio/vm, which required an ad-hoc evaluation of component JSON properties. To ensure that the timeout is able to be configured for all evaluations, the `configureVM` method was refactored to include a global timeout. This PR updates the downstream code to correspond to those changes made in [@formio/vm#35](https://github.com/formio/vm/pull/35).
n/a
* https://github.com/formio/vm/pull/35
n/a
=> FIO-9064: refactor configureVm to include global timeout, remove timeout from other evaluate args

src/db/index.js, src/db/updates/2.4.2.js, src/middleware/submissionHandler.js
https://formio.atlassian.net/browse/FIO-9099
Some changes made recently in #1766 didn't account for breaking changes in the MongoDB drivers, which no longer return an `ops` object from the `insertOne` method. This was causing an issue during schema and lock creation. This PR updates the lock creation function as well as fixes some other minor async JS issues.
n/a
n/a
manually
=> FIO-9099: fix various async problems

src/util/conditionOperators/IsNotEqualTo.js, test/actions.js
https://formio.atlassian.net/browse/FIO-9121
Additional processing for select boxes components was added in IsNotEqualTo condition.
manually,
autotests
=> FIO-9121: added check for select boxes components IsNotEqualTo condition

src/export/exporters/CSVExporter.js
https://formio.atlassian.net/browse/FIO-9087
Changed CSV export behavior to return actual signatures data values or an empty string if value is nonexistent instead of 'yes' or 'no'. 
Tested manually
=> FIO-9087: fixed an issue where the app does not implement signature yes or no filter

src/middleware/lastModifiedIndexHandler.js, src/middleware/middleware.js, src/resources/FormResource.js, test/form.js
https://formio.atlassian.net/browse/FIO-9006
**Issue**: The issue is described in this [PR](https://github.com/formio/angular/pull/1104). As mentioned, it's not a good idea to simply disable the cache. Instead, we can use the `Last-Modified` response header to get the last modified date of the requested forms.
**Solution**: Apply filters from the original request and find the last date of any modification (create, update, delete) in that selection. Set this date as the `Last-Modified` response header. The browser will use this to set the `If-Modified-Since` request header in future requests. If there are no modifications since this time, the server will respond with a 304 status code.
Added the ability to check the execution timing using the PERFORMANCE_TIMER environment variable.
Unit …
=> FIO-9006: Added Last-Modified response header on form index request

src/cache/cache.js
https://formio.atlassian.net/browse/FIO-9306
The 'loadSubSubmissions' does not wait when all subSubmissions are loaded. This causes the formio-server to send a submission object without subSubmissions attached to pdf-server. This PR fixes it.
There is no this issue on the master branch as master does not use callbacks.
Manually with pdf-server.
=> 4.2.x-4.3.x - FIO-9306: fixed an issue where nested forms do not show data in PDF

src/util/util.js
https://formio.atlassian.net/browse/FIO-9365
`Validator` constructor now allows passing `req` object lacking `headers`, `query` or `params`
the fact that it's not going to throw now is a breaking change technically, but I don't think it's going to affect anybody
n/a
Tested in sandbox
=> FIO-9365: allow incomplete req object for Validator constructor

src/actions/fields/form.js, test/submission.js
https://formio.atlassian.net/browse/FIO-9308
The issue only occurs if there are two nested forms that have keys that "startWith" the same characters. Such as "form" and "form1".  In this case, the data of "form1" could be affected if the conditions of "form" are conditionally hidden. In this case the "startsWith" actually returns true because "form1" starts with "form". 
I solved this problem by changing the "startsWith" to take into account that this may be a "parent" path which would always contain either a "." or a "[" in the startsWith check. This ensures that the following will be true.
"container.form" => will pass if the container is conditionally hidden since "container.form" starts with "container."
"form" => will not pass since "form1" does NOT start with "form."
None
None
A new …
=> FIO-9308: Fixed an issue where nested forms that start with the same keys submit the wrong data.

index.js
https://formio.atlassian.net/browse/FIO-9473
Containers failed to start because deprecating mongoose options were being used.
n/a
n/a
n/a
=> hotfix: update mongoose connection options

src/db/index.js
n/a
Upon a db related error, the server will attempt to unlock. This will fail in the case of e.g. database connection errors, because there is no database to unlock. This PR updates error handling to throw the correct error rather than always throwing the unlock error. 
n/a
n/a
n/a
=> CHORE: update error handling to not throw lock error

src/export/exporters/CSVExporter.js, test/export/CSVExporter/CSVExporter.js
https://formio.atlassian.net/browse/FIO-9471
*Fixed an issue with displaying Wizard form data on CSVExport. Previously, the data was not displayed for Wizard forms, because the mapping was changed*
*n/a*
*n/a*
*Automated test has been added. All tests pass locally*
=> FIO-9471 fixed CSVExport for wizard forms

src/cache/cache.js
https://formio.atlassian.net/browse/FIO-9528
After pathing change tha was implemented recently, eachComponent utility function's parameter called 'path' is no longer a data path of the component, but rather a complete path to the component inside form's JSON schema (including all the layout components keys), so loadSubSubmissions function now should use compPaths object containing all the possible component's paths to get a dataPath and then get component's data using it.
*Use this section to describe how you tested your changes; if you haven't included automated tests, …
=> FIO-9528: Fixes an issue where nested forms submissions are not preloaded and do not appear in the PDF downloads

portal/src/components/NewForm.tsx
https://formio.atlassian.net/browse/FIO-9578
fixed an issue where resource is created as a form in OSS portal. We need explicitly pass the form type to the react builder component.
=> FIO-9578: fixed an issue where resource is created as a form in OSS portal

package.json, test/actions.js, test/util.js, yarn.lock
https://formio.atlassian.net/browse/FIO-9499
Updated `@formio/vm` to include a browser mock for the `NodeList` object. When `formio` tried rendering an email template containing an edit grid, it called the `deatch()` method on the `Component` class in `formio.js`, which referenced the `NodeList` object, which was undefined on the server. I've updated `@formio/vm` with a mock for when `formio.js` code is executing server-side.
See `@formio/vm` PR.
n/a
https://github.com/formio/vm/pull/45
Automated test that fires an email action to render an email template representing a submission containing an edit grid.
=> FIO-9499: Add test for email action with edit grid

src/export/exporters/CSVExporter.js, test/export/CSVExporter/CSVExporter.js
https://formio.atlassian.net/browse/FIO-9471
*The issue of displaying data on the CSV Export page is relevant not only for Wizard Forms, but also for regular Forms with components that are located inside the Component Layout. The problem was fixed by searching the submission data using dataPath.*
*n/a*
*n/a*
*Automated test has been added/ All tests pass locally*
=> FIO-9471fixed the display of data for components inside layout components

src/models/Submission.js
https://github.com/formio/formio/issues/1925
Remove schema.index calls
This was causing warning on startup
We already create these indexes with
model.schema.index(hook.alter('schemaIndex', {deleted: 1}));
model.schema.index(hook.alter('schemaIndex', {form: 1, deleted: 1}));
model.schema.index(hook.alter('schemaIndex', {form: 1, deleted: 1, created: -1}));
N/A
N/A
manually tested
=> GH-1925: removed duplicate index creation

src/actions/EmailAction.js, src/util/email.js
https://formio.atlassian.net/browse/FIO-9789
At some point, we attempted to add rate limiting to our email action, but took the wrong approach.
```javascript
const throttledSendEmails = _.throttle(sendEmails , NON_PRIORITY_QUEUE_TIMEOUT);
/* ... */
if (!req.user) {
try {
throttledSendEmails();
}
catch (err) {
debug.error(err);
throw new Error(err);
}
} else {
try {
const response = await sendEmails;
return response;
}
catch (err) {
debug.error(err);
throw new Error(err);
}
}
```
This has a couple of issues:
1. This doesn't meaningfully rate limit across requests; `sendEmails` is always only called once per request, so each "throttled" function will be created anew with each subsequent request, meaning the rate limiting problem is still there.
2. Since `_.throttle` returns a synchronous …
=> FIO-9789: update needless synchronous throttle to fix error handling in email action

src/middleware/submissionHandler.js, src/resources/Validator.js, test/submission.js
https://formio.atlassian.net/browse/FIO-9814
We use case insensitive regex queries to evaluate uniqueness for string-based components. Indexes on this type of query don't really do much for you, so this is potentially very slow given a large dataset. So, for things like login and registration where we have to do searches for emails over a > 1TB dataset (e.g. in our SaaS environment), we need a way to make this faster, so for email components (and text components with a certain regex pattern) - where we're pretty certain the local will be 'en' -  we leverage collation-aware searching.
However, this was incorrectly implemented in the unique validation subroutine - this PR updates the logic to use our feature detection flag to ensure we _can_ use collation-aware search before we pull the …
=> FIO 9814: fix problem with unique validation for email components

src/export/exporters/CSVExporter.js, test/export/CSVExporter/CSVExporter.js, test/fixtures/forms/formWithLayoutComponents.js
https://formio.atlassian.net/browse/FIO-9952
The changed eachComponent returns the full component path that includes layout components. But the CSV export expects the value path (as it was in 4.x.) so that CSV import works fine. This PR fixes it.
Manually + autotests
=> FIO-9952: fixed components paths in  CSV export

src/resources/Validator.js
https://formio.atlassian.net/browse/FIO-9946
Recently, we fixed a bug with the Data Table with the following PR https://github.com/formio/formio/pull/1749.  This pull request ensures that the components that are used to submit the data table only include the components that are configured for the data table component to ensure that the data matches the row (so it can be selected). The problem with this code is that it does not account for the components structure of the columns and table components. I made some changes that resemble the "eachComponent" method. We may consider moving this code into core, but for now, I will fix it here so that we can get through the blocker.
None
None
Manual test for now. Will submit a new unit test later.
=> FIO-9946: Fixing issues with data table submissions with columns and tables.

portal/src/components/FormView/FormActions.tsx, src/actions/actions.js, test/actions.js
https://formio.atlassian.net/browse/FIO-9943
On the client side: a check has been added to determine whether method and handler can be entered in the form. If this is not provided for current type of action, default values are set.
On the server side, a check has been added for missed  method and handler data, and default values are set.
-
-
manually
autotests
=> FIO-9943: fix save submission action on Open Source Portal

portal/public/style.css
https://formio.atlassian.net/browse/FIO-9676
Footer was taking too much space on the screen, made it go down a bit a make the builder take all the space available 
=> FIO-9676: Fixes foot height in the OS portal

.github/workflows/ci.yml, package.json
https://formio.atlassian.net/browse/FIO-9783
Replace `postinstall` with `prepare` so that webpack is not run when library is installed as a dependency.
=> FIO-9783: add prepare step instead of postinstall (4.5.x)

src/util/util.js
https://formio.atlassian.net/browse/FIO-10052
Updates the coeerceQueryTypes function to account for the fact that `getComponent` called with a selectboxes component's value (e.g. `getComponent(`mySelectBoxes.mySelectBoxesValue`) will return the selectboxes component (see [@formio/core#253](https://github.com/formio/core/pull/253))
Completes the solution provided in [formio-monorepo#132](https://github.com/formio/formio-monorepo/pull/132) while we're syncing over to the monorepo
=> FIO-10052: sync monorepo change re: selectboxes component

src/util/conditionOperators/index.js
https://formio.atlassian.net/browse/FIO-10236
The change with removing Formio.AllComponents usage was left by accedent wich caused an issue where Value component would not change its type/settings after choosing a component inside 'When' field in the Action Conditions form.
manually tested Action Conditions form
=> FIO-10236: Fixes an issue where Value component does not change type in the Action Conditions form

index.js, src/vm/index.js
https://formio.atlassian.net/browse/FIO-10237
We have the need to dynamically inject enterprise features into the VM sandbox (because e.g. our Reporting UI feature introduces some globals that we need). The new VM paradigm - in which we execute evaluations on demand rather than relying on the VM to execute the entire form orchestration process - means that we need Enterprise Server to tell us when we should inject this dependency. This PR introduces the ability for the `IsolateVMEvaluator` to call our hook system so that the Enterprise features can be injected if applicable.
n/a
n/a
I've added automated tests.
=> FIO-10237: update IsolateVMEvaluator to leverage hook system for Enterprise features

src/db/index.js
https://formio.atlassian.net/browse/FIO-10043
Added indexes ({"$**": 1}) to ensure support for sorting on arbitrary fields in CosmosDB for situations where it is necessary.
-
-
manually
=> FIO-10043: automatically adding indexes for CosmosDB

src/util/email/utils.js
https://formio.atlassian.net/browse/FIO-10478
Emails with select component are blocked to send as this PR (https://github.com/formio/formio-monorepo/pull/211/files) was not fully cherry-picked to 4.5.x and cleanLabelTemplate was undefined. This PR adds the missing code. Master branch works ok.
=> 4.5.x - FIO-10478: fixed an issue where emails are not sent for forms for select component
