- package.json
- src/authentication/index.js
- src/middleware/deleteActionHandler.js
- src/middleware/deleteFormHandler.js
- src/middleware/deleteRoleHandler.js
- src/middleware/deleteSubmissionHandler.js
- test/actions.js
- test/auth.js
- test/form.js
- test/resource.js
- test/roles.js
- test/submission.js
Fixes FA-476 and FA-479.
Dependent for: https://github.com/formio/formio-server/pull/47
> Updating tests and resourcejs version for 204 to 200 changes.

- circle.yml
- package.json
> Adding jscoverage.

- src/actions/EmailAction.js
- src/actions/macros/macros.js
- src/actions/macros/table.txt
This adds a ```table``` macro to the email that will build a table view for the submission data for placement in an email, like this.
```{{ table(form.components) }}```
> Add macros to the emails that get sent

- package.json
- src/util/email.js
ready for review/merge.
used for: https://github.com/formio/formio-app/pull/238
> Adding sendgrid api key support.

- package.json
- src/db/updates/2.4.1.js
- src/export/export.js
- src/middleware/filterProtectedFields.js
- src/middleware/submissionHandler.js
- src/resources/SubmissionResource.js
- src/util/util.js
> PRODFIX - Do not expose the signature within index queries

- src/actions/actions.js
> Updating the generated action form, to have api keys for all components.

- src/middleware/mergeFormHandler.js
- src/middleware/middleware.js
- src/models/Form.js
- src/resources/FormResource.js
- test/form.js
Uses: https://github.com/formio/formio.js/pull/36 and https://github.com/formio/formio-app/pull/419
> Feature/for 251 - Adding initial form collaboration/merge functionality

- src/actions/WebhookAction.js
- test/actions.js
> Feature/for 197 - Trial

- src/middleware/submissionHandler.js
- src/resources/Validator.js
- test/form.js
- test/forms/customValidation.js
Uses: https://github.com/formio/ngFormio/pull/271
> Bugfix/for 255 - Updating and fixing the component custom validation

- package.json
- src/resources/FormResource.js
- test/form.js
- test/forms/for278.js
Dependent on: https://github.com/travist/resourcejs/pull/60
Rerun the tests once its merged and `1.6.0` is released
> Bugfix/for 278 - Some number components cant have a min value set

- src/export/exporters/CSVExporter.js
This also adds some crude datagrid export functionality for csv and cleans up the selectboxes and survey components when exported.
> Bugfix/for 308 - Fixing issue with address components (multi) and csv exports

- package.json
- src/db/updates/3.0.7.js
- src/models/Form.js
- test/form.js
- test/helper.js
Dependent on https://github.com/formio/formio-server/pull/210
> Bugfix/for 326 - Fixing form types

- src/resources/FormResource.js
- src/resources/RoleResource.js
- src/templates/import.js
- test/actions.js
- test/form.js
- test/helper.js
- test/roles.js
> Bugfix/for 321 - Fixing export and import code

- src/resources/FormResource.js
- src/resources/SubmissionResource.js
- test/helper.js
This allows modifying the Resource factory to add new functionality.
> Allow altering the Resource for forms.

- src/resources/Validator.js
> Remove validators for non-persistent fields.

- src/util/email.js
Fix issue where username and password were required for smtp connections. Smtp does not require them and some people set this up without.
> Anonymous SMTP

- src/db/updates/3.0.0.js
- src/models/Role.js
- src/plugins/machineName.js
- src/util/util.js
> Fixed the machine names to be performant and without special chars.

- src/util/email.js
Set the flag tls -> rejectUnauthorized to false, if you wont to allow usage of self signed certificates on smtp server
> allow usage of Unauthorized certificates

- src/actions/fields/form.js
`Validator` works correctly and skips hidden field on the parent form.
> Fix issue when we validate subform even when it hidden

- package.json
- src/actions/WebhookAction.js
- src/db/updates/2.4.1.js
- src/middleware/filterProtectedFields.js
- src/util/util.js
- test/actions.js
- test/submission.js
> Revert "Always make sure to protect the password fields."

- src/export/export.js
Fixes issue with server crash during CSV exports.
Suspect it will also fix https://formio.atlassian.net/browse/FOR-2359.
> Separate DB cursor end and output stream end by a tick

- src/middleware/accessHandler.js
- test/form.js
> Revert "Limit /access return data by project and form read access"

- src/middleware/accessHandler.js
- test/form.js
> Revert "[rebased] Limit /access return data by project and form read access"

- src/middleware/tokenHandler.js
Adds support for defining API keys as environment variable, thus making the API server compatible with form.io's portal API Keys.
> added api token support

- README.md
* per https://github.com/mongodb/homebrew-brew
> update readme to reflect mongodb-community

- src/export/export.js
- Added DB cursor error handling
- Fixes issue https://github.com/formio/formio/issues/976
> [Critical] Fixed server crash on invalid x-query

- src/db/index.js
> Add options to use SSL Certs with Mongo connection.

- src/actions/WebhookAction.js
> Fixes issue #939

- src/middleware/middleware.js
- src/middleware/storageAccessHandler.js
That is new middleware that checks if user roles contain group resource id. The middleware also supports group permission levels.
> FOR-2699: added storageAccessHanler to check storage permissions

- src/middleware/permissionHandler.js
fixed another bug with index request
> 112 split roles bug fixes

- src/middleware/submissionHandler.js
> FOR-2837: Fixes an issue where for validating a submission with a form revision always was getting the latest version of the form.

- src/templates/default.json
related to https://github.com/formio/formio-server/pull/675
> FOR-2762: Changes default permissions for a new project

- src/actions/actions.js
- src/models/ActionItem.js
- src/models/BaseModel.js
- src/models/Form.js
- src/models/Submission.js
- src/plugins/timestamps.js
> Revert "Adding expiring action items."

- src/models/Form.js
> Revert "Changed field match access schema to have splitted permissions instead"

- src/actions/EmailAction.js
- src/actions/ResetPassword.js
- src/util/email.js
- test/auth.js
- test/fixtures/template.js
Must be merged after https://github.com/formio/formio-server/pull/785
> FIO-1528: FIO-1528: change default 'from' email address domain to use example in the deployment environment variable

- src/middleware/submissionHandler.js
Prevent calling done() multiple times when send a submission with reCaptcha
> FIO-2975: ReCaptcha is causing the server to crash

- test/actions.js
Tests for https://github.com/formio/formio-server/pull/842
> FIO-3040: Adds tests for FIO-3040 when wasn't handle the Webhook error and respond instead of spinning forever.

- src/util/util.js
https://github.com/formio/formio/issues/1283
> Improve validation perf. by moving VM instance outside Evaluator

- index.js
> Revert "Quick fix to point the issue"

- src/middleware/formHandler.js
> Revert "Legacy bad chacracters filtering removed"

- src/cache/cache.js
- src/middleware/submissionHandler.js
> Revert "FIO-4216: 'Resource not found' when get submission form submission collection"

- src/middleware/permissionHandler.js
- src/middleware/submissionResourceAccessFilter.js
Fixed an issue where users having permission to read submission are not able to see them because they also have create/update/delete permission with the same role
> Fixes Group Permissions issue

- src/resources/Validator.js
Related PR: https://github.com/formio/formio-server/pull/1049
> Added support to the allowAllSubmissionData setting

- src/middleware/submissionHandler.js
- src/util/util.js
- Added null check around checking the components in the event that a null component were to ever be added to a form to prevent the server from crashing
> FIO-5756: PDF | Regression | FFT 502 Bad gateway error after Click on submit

- src/actions/fields/datetime.js
> Revert "FIO-5233: fixed an issue with incorrect values in different timezones…"

- Changelog.md
*Previously, formio ... This PR replaces this behavior by ...*
*Although there were many potential solutions such as ..., [my solution] was best because ...*
> Update Changelog.md - Updated to 3.2.0-rc.1 and additions

- Changelog.md
*Previously, formio ... This PR replaces this behavior by ...*
*Although there were many potential solutions such as ..., [my solution] was best because ...*
> Update Changelog.md - dependabot updates

- test/submission.js
A test for https://github.com/formio/formio.js/pull/5092
Edit: Now a test for https://github.com/formio/formio.js/pull/5200
> FIO-4809: Added a test

- src/resources/SubmissionResource.js
https://formio.atlassian.net/browse/FIO-6840
A performance bottleneck in the user registration process was due to inefficient case-insensitive regex queries being used throughout the codebase. This PR updates the `/exists` endpoint, given a query string `ignoreCase`, to utilize the more efficient indexing scheme. It's pretty hacky, and probably should be refactored ASAP.
https://github.com/formio/formio.js/pull/5244
https://github.com/formio/formio/pull/1590
https://github.com/formio/formio-app/pull/1470
https://github.com/formio/formio-server/pull/1278
This is a high priority and something of a hotfix, so I was unable to write automated tests for this.
> FIO-6840: change to allow case insensitive exists endpoint

- src/middleware/addSubmissionResourceAccess.js
- src/middleware/formRevisionLoader.js
- src/middleware/permissionHandler.js
- src/middleware/setFilterQueryTypes.js
- src/middleware/submissionHandler.js
- src/middleware/tokenHandler.js
- src/util/util.js
- test/submission.js
https://formio.atlassian.net/browse/FIO-7067
Fixed issue with id parsing
Unit tests
> FIO-7067: fixed issue with id parsing and eslint warnings

- src/middleware/addSubmissionResourceAccess.js
- test/submission.js
https://formio.atlassian.net/browse/FIO-7067
Added empty object validation.
Unit test
> FIO-7067: fixed issue with empty value for patch request

- src/authentication/index.js
- src/db/index.js
- src/db/updates/3.1.5.js
- src/resources/SubmissionResource.js
*Previously, formio ... This PR replaces this behavior by ...*
*Although there were many potential solutions such as ..., [my solution] was best because ...*
> Adding a mongodb feature check to core.

- package.json
*Previously, formio ... This PR replaces this behavior by ...*
*Although there were many potential solutions such as ..., [my solution] was best because ...*
> Correct rc version

- src/resources/Validator.js
- test/fixtures/forms/wizardFormWithAdvancedConditions.js
- test/submission.js
https://formio.atlassian.net/browse/FIO-7351
*Fixed submitting data for the Panel component if the conditionals are applied for Panel for Wizard.*
*no*
*All tests pass locally. Also, the case for https://formio.atlassian.net/browse/FIO-5731 has been tested (works as expected). Automated tests have been updated.*
> FIO-7351 fixed submitting data using Wizard with conditionals for Panel component

- src/actions/EmailAction.js
https://formio.atlassian.net/browse/FIO-7344
Changed Rendering method tooltip to remove 'deprecated' message
Tested locally
> FIO-7344 Changed Rendering method tooltip

- src/middleware/filterProtectedFields.js
- src/middleware/filterResourcejsResponse.js
- src/util/util.js
https://formio.atlassian.net/browse/FIO-7371
Added hook calls to some middlewares that filter out fileds in response data to not let them do so if the hook returns true.
I've found middlewares that filter out some fields from response data and let them skip under certain condition.
[formio-server:1352](https://github.com/formio/formio-server/pull/1352)
I've added automated tests.
> FIO-7371: Adds checks to define if raw DB data should be returned in response

- package.json
- src/actions/SaveSubmission.js
- src/actions/actions.js
- src/util/util.js
https://formio.atlassian.net/browse/FIO-7543
This reverts https://github.com/formio/formio/pull/1643 out of the master branch of formio OSS. Previously it was only removed from the 3.4.x and 3.3.x branches and we have decided to pull it out completely while we continue working on solutions for vm2.
https://github.com/formio/formio-server/pull/1391
https://github.com/formio/formio-workers/pull/51
> FIO-7543: Revert isolated vm changes (#1650)

- src/db/index.js
https://formio.atlassian.net/browse/FIO-7482
Added function that performs DB updates of the default configuration forms. Currently we have only one form that is expected always to correspond to the server version, that is reportingUI.
https://github.com/formio/formio-server/pull/1393
> FIO-7482: added ability to update default configuration forms in db to the versions required by the server (required for reportingUI form)

- src/actions/SaveSubmission.js
- src/actions/actions.js
- src/cache/cache.js
Reverts https://github.com/formio/formio/pull/1615
> revert changes related to FIO-7125 feature

- config/default.json
- package.json
- src/util/email.js
- src/util/util.js
https://formio.atlassian.net/browse/FIO-7549
https://formio.atlassian.net/browse/FIO-7652
https://formio.atlassian.net/browse/FIO-7653
https://formio.atlassian.net/browse/FIO-7654
Reason for changes
https://www.cve.org/CVERecord?id=CVE-2023-45857
Removed `mailgun.js` and  `sendgrid` that has dependency on axios that caused the CVE issue and breaks tests. 
Removed
[mailgun.js](https://www.npmjs.com/package/mailgun.js)
[@azure/ms-rest-nodeauth](https://www.npmjs.com/package/@azure/ms-rest-nodeauth)
[@sendgrid/mail](https://www.npmjs.com/package/@sendgrid/mail)
Tested locally, tests pass.
> FIO-7549: evaluate axios upgrades and CVE resolution

- Dockerfile
- docker-compose.yml
- package.json
- src/actions/actions.js
Update Docker Alpine Linux to latest, and fetch latest make and g++ from alpine apk repos.
Also docker-compose syntax to use of v2 `docker compose` instead of `docker-compose`
- Also related: https://github.com/formio/formio/issues/1665#issuecomment-1854259250
I am leaving PR to be editable by maintainers, to make nitpicks where needed.
- Alpine Linux LTS
- Docker Compose v1 -> v2 syntax
- Node Engine >=18.x
- To make oss docker builds working again.
- Yes, I have tested building and running docker imager, and they were online flawlessly.
> Update Docker Configs

- src/resources/Validator.js
https://formio.atlassian.net/browse/FIO-7823
An error was occurring within the server-side form validation subroutine and bubbling up to crash the server. The cause of this error was fixed in [formio.js#5479](https://github.com/formio/formio.js/pull/5479) but its important to ensure that errors in the renderer are caught. 
Although I'm not certain why the existing `.catch()` blocks are not sufficient here, my guess is that it might be due to the fact that the 4.x renderer uses a Promise polyfill that may not properly implement Promise chain catch blocks. In any case, manual testing has shown that an overarching try/catch block should catch the most egregious of errors and return the error to the client rather than crashing the server.
n/a
n/a
Manually
> FIO-7823: add error boundary around server-side form validation

- src/middleware/permissionHandler.js
https://formio.atlassian.net/browse/FIO-7292
We have special entity with 'submission' type and empty id to check file permissions. So added missing delete check to have ability delete file from storage with delete_own permission.
> FIO-7292: Added own check to delete file from storage

- src/middleware/submissionHandler.js
- src/resources/Validator.js
https://formio.atlassian.net/browse/FIO-7998
Adds captcha validation back to the new @formio/core based server-side validation
* [@formio/core#46](https://github.com/formio/core/pull/46)
n/a
> FIO-7998: add captcha validation

- test/submission.js
https://formio.atlassian.net/browse/FIO-7958
Fixes tests based on dependent core changes (see comments below each change)
[@formio/core#45](https://github.com/formio/core/pull/45)
n/a
> FIO-7958: fix tests to be compatible with core validation

- src/resources/Validator.js
https://formio.atlassian.net/browse/FIO-8042
Propagate processors scope through the submission object
none
manually
> FIO-8042: attach scope to the submission object

- src/db/index.js
https://formio.atlassian.net/browse/FIO-7522
Removed DB_SECRET migration logic and added hook call.
Moves logic to server project
None
Tested with supporting branch.
> FIO 7522 Encrypted Fields Not Re-Encrypted to New DB Secret

- src/actions/actions.js
- src/util/hook.js
https://formio.atlassian.net/browse/FIO-8145
Copy of https://github.com/formio/formio/pull/1727
https://github.com/formio/formio-server/pull/1469
> FIO-8087: Fixes an issue where Email Action with logs enabled don't render nested form value and shows ID instead

- src/util/email.js
https://formio.atlassian.net/browse/FIO-8235
Configurable timeout added to email rendering
https://github.com/formio/vm/pull/24
unit tests passing
> FIO-8235: add timeout to email rendering

- index.js
- package.json
- src/util/staticVmDependencies.js
- yarn.lock
https://formio.atlassian.net/browse/FIO-8251
*added inputmask library to vm configuration*
*no*
*https://github.com/formio/vm/pull/25*
*locally*
> FIO-8251 added inputmask library

- src/export/exporters/CSVExporter.js
- test/export/CSVExporter/CSVExporter.js
- test/fixtures/forms/timeDateComponent.js
https://formio.atlassian.net/browse/FIO-7866
Fixed issue related to server crash while CSV exporting data related to forms containing DateTime components into Edit or Data Grid. Removed extra quotes in export results.
No dependencies
Automation tests were added
> FIO-7866: date time component with display in timezone of submission in data or edit grid issue fix

- Dockerfile
> fix: change client to portal

- package.json
- src/resources/Validator.js
- src/templates/import.js
- test/submission.js
- yarn.lock
n/a
Updates dependencies for 5.x renderer upgrade
n/a
[@formio/core#129](https://github.com/formio/core/pull/129)
n/a
> Upgrade 5.x renderer

- src/middleware/submissionHandler.js
- test/submission-access.js
https://formio.atlassian.net/browse/FIO-8643
Fixed data handling for component with client-only persistent type.
-
-
autotests
> FIO-8643: removed erroneous appearing client only field data in submission

- src/util/conditionOperators/index.js
https://formio.atlassian.net/browse/FIO-8851
https://formio.atlassian.net/browse/FIO-8898
https://formio.atlassian.net/browse/FIO-8850
https://formio.atlassian.net/browse/FIO-8859
https://formio.atlassian.net/browse/FIO-8854
Made some components unavailable for simple conditionals + removed some properties from the conditions value field
https://github.com/formio/premium/pull/322
Manually
> FIO-8851-8898-8850-8859-8854: fixed simple conditions issues

- src/actions/fields/form.js
- test/submission.js
https://formio.atlassian.net/browse/FIO-8810
Improved the condition check for nested form so that it could define that the nested form inside conditionally hidden nested components (e.g. another nested form or container) is also considered as hidden.
https://github.com/formio/core/pull/139
Manually + tests
> FIO-8810: fixed an issue where the conditional nested form with several nested levels with required fields cannot be submitted when hidden

- src/middleware/submissionHandler.js
https://formio.atlassian.net/browse/FIO-8295
Added check for sending response in case of an error when processing submission.
-
-
auto tests and manually
> FIO-8295: duplicate res sent removed

- src/util/conditionOperators/DateGreaterThan.js
- test/actions.js
https://formio.atlassian.net/browse/FIO-9145
Problem with DateFormat setting for created and modified submission parameters (not component) was fixed.
manually,
autotests
> FIO-9145: fixed DateFormat setting for created and modified submission parameters

- src/util/conditionOperators/index.js
https://formio.atlassian.net/browse/FIO-8866
Use  Formio.Components.components for iteration as it includes premium components
> FIO-8866: fixed an issue where action conditions UI shows incorrect operators for premium components

- src/cache/cache.js
https://formio.atlassian.net/browse/FIO-9181
Before, when the submission refers to the same resource several times (e.g the form has COUNTRY select resource with 'save as reference' enabled and this field is used several times in the form and in the nested forms and it is equal to USA in several fields), the reference was attached only to the last field that caused issues with value display and dependent conditions executions in PDF download . It is because subs object inside loadSubSubmissions has a structure like 
{
refID: { ...componentInfo }
}. 
This PR changes the subs structure to 
{
refID: [ {...component1Info}, {...component2Info} ... ]
}
and makes all corresponding changes so that it works.
Manually in connection with PDF server to make sure that all data is …
> 4.3.x-4.2.x: FIO-9181: fixed an issue where component reference is not attached if several form componets refers to the same submission

- src/cache/cache.js
https://formio.atlassian.net/browse/FIO-9181
Before, when the submission refers to the same resource several times (e.g the form has COUNTRY select resource with 'save as reference' enabled and this field is used several times in the form and in the nested forms and it is equal to USA in several fields), the reference was attached only to the last field that caused issues with value display and dependent conditions executions in PDF download . It is because subs object inside loadSubSubmissions has a structure like
{
refID: { ...componentInfo }
}.
This PR changes the subs structure to
{
refID: [ {...component1Info}, {...component2Info} ... ]
}
and makes all corresponding changes so that it works.
https://github.com/formio/formio/pull/1824
Manually in connection with PDF …
> master - FIO-9181: fixed an issue where component reference is not attached if several form components refers to the same submission

- src/util/delete.js
- test/actions.js
https://formio.atlassian.net/browse/FIO-9337
*Updating the code and adding tests*
*n/a*
*n/a*
*Automated tests have been added. All test pass locally*
> FIO-9337 code updates

- src/util/util.js
- test/submission.js
https://formio.atlassian.net/browse/FIO-8431
Formation of the path to the components included in the tagpad (additional data field) was changed (data field in dot object is taken into account)
Algorithm of deleting protected data has been updated (processing of data nested in an array has been added)
autotests
> FIO-8431: fixed behavior of tagpad internal protected components

- package.json
- yarn.lock
n/a
Upgrades the mongodb driver dependency.
n/a
[resourcejs#150](https://github.com/travist/resourcejs/pull/150)
n/a
> CHORE: upgrade mongodb driver dependency

- src/cache/cache.js
https://formio.atlassian.net/browse/FIO-9436
https://formio.atlassian.net/browse/FIO-9437
https://formio.atlassian.net/browse/FIO-9481
Wait when subSubmissions are downloaded.
> FIO-9436-9437-9481: wait subSubmissions to load

- package.json
- yarn.lock
> Update core to 2.4.0-rc.4

- src/export/exporters/CSVExporter.js
- test/export/CSVExporter/CSVExporter.js
https://formio.atlassian.net/browse/FIO-9472
The issue related to component path refactoring, changed how we handle nested form for csv export and added tests.
n/a
n/a
Tested manually and added automated tests.
> FIO-9472: fixed nested component form values in CSV

- package.json
- src/middleware/submissionHandler.js
- yarn.lock
https://formio.atlassian.net/browse/FIO-9503
Made executeFieldHandlers go before executeActions
So that the nested form gets its data back before the email action is executed
N/A
N/A
Writing a test in formio-server
> FIO-9503: fixed nested form data not appearing in emails

- portal/public/style.css
- portal/src/components/App.tsx
- portal/src/components/InfoPanel/ActionsPanel.tsx
- portal/src/components/InfoPanel/CreatePanel.tsx
- portal/src/components/InfoPanel/Partials/EvaluationLicenseInfo.tsx
- portal/src/components/InfoPanel/UsePanel.tsx
- portal/src/components/InfoPanel/ViewDataPanel.tsx
- portal/src/components/NewForm.tsx
https://formio.atlassian.net/browse/FIO-9574
https://formio.atlassian.net/browse/FIO-9576
- added info panel for the new form page, fixed styles
- made the license contact detail a separate component as it is repeated in many info panels and fixed link for contact page.
> FIO-9574-9576: fixed info panel on the new form page and fixed the info panels contact btn

- package.json
- yarn.lock
https://formio.atlassian.net/browse/FIO-9507
Update version
Generate a fresh dev tag to filter up the dependency tree
n/a
https://github.com/formio/core/commit/49ab979f5f041fb26ce43d264a843177a5465bb2
https://github.com/formio/bootstrap/pull/120
https://github.com/formio/formio.js/pull/5977
https://github.com/formio/vm/pull/40
~~https://github.com/formio/formio.js/pull/5979~~
n/a
> FIO-9507 Update formio main branch

- portal/src/components/FormView/FormActions.tsx
https://formio.atlassian.net/browse/FIO-9593
fixed link
> FIO-9593: fixed actions docs link

- portal/public/style.css
- portal/src/components/FormList.tsx
https://formio.atlassian.net/browse/FIO-9572
- made tooltip work
- fixed links and description for tooltip text
> FIO-9572: fixed help tooltip does not show any information in oss portal

- src/export/exporters/CSVExporter.js
- test/export/CSVExporter/CSVExporter.js
https://formio.atlassian.net/browse/FIO-9471
*Fixed an issue with displaying data for components inside Layout components  on CSVExport. Previously, the data was not displayed, because the mapping was changed*
*n/a*
*n/a*
*Automated tests have been added. All tests pass locally*
> FIO-9471fixed the display of data for components inside layout components

- .github/workflows/ci.yml
- .gitignore
- docker-compose.yml
- portal/src/components/Layout.tsx
- portal/tsconfig.json
> Adding github jobs to support automated builds of Docker containers.

- docker-compose.yml
- portal/public/style.css
- portal/src/components/Layout.tsx
n/a
Update the portal application CSS to un-break the footer.
n/a
n/a
n/a
> update CSS to un-break footer

- .github/workflows/ci.yml
- .gitignore
- config/default.json
- docker-compose.yml
- package.json
> Updates to Docker compose and docker deployments.

- Changelog.md
- yarn.lock
> Update mongoose dep to 8.9.5

- portal/src/components/FormList.tsx
- portal/src/components/FormView/EditForm.tsx
- portal/src/components/FormView/index.tsx
https://formio.atlassian.net/browse/FIO-9701
Added additional prop for EditForm that update the form data for top level component after the form changes are saved.
Removed initialForm when the form url is changed, to prevent multiple redrawing (when page 'jumps') of the editForm.
Made form list redirect to the edit page to prevent unnecessary page reloading after form saving.
> FIO-9701: fixed an issue where the form title is not updated on the edit page after form is saved/fixed unnecessary edit page redrawing

- src/resources/SubmissionResource.js
- test/fixtures/forms/singlecomponentsSimple.js
- test/submission.js
https://formio.atlassian.net/browse/FIO-9771
Made submission Patch update the modified date
None
Automated test added
> FIO-9771: make submission PATCH update the modified date

- package.json
- test/actions.js
- test/submission.js
- yarn.lock
https://formio.atlassian.net/browse/FIO-8250
Added test to cover input mask validation.
n/a
https://github.com/formio/vm/pull/53
> FIO-8250: added test for input mask validation

- package.json
- test/actions.js
- test/fixtures/forms/selectComponent.js
- yarn.lock
https://formio.atlassian.net/browse/FIO-9532
For changes check dependencies. This PR adds tests.
n/a
https://github.com/formio/vm/pull/54
https://github.com/formio/formio.js/pull/6043
tested locally, automated tests added
> FIO-9532: added tests for select component showing values instead of labels

- test/validator.js
https://formio.atlassian.net/browse/FIO-9946
Adding tests for the datatable with columns or table bug that was recently fixed.
None
None
Automated test written.
> FIO-9946: Adding tests for datatable w/ columns and tables.

- portal/src/components/FormView/FormAccess.tsx
- portal/src/components/FormView/FormActions.tsx
https://formio.atlassian.net/browse/FIO-10036
Fixed build errors for OSS portal
https://github.com/formio/core/pull/246
> FIO-10036: fixed types for OSS portal

- install.js
- package.json
- yarn.lock
https://formio.atlassian.net/browse/FIO-10083
The 'prompt' library has not been updated for a long time so replaced it with a modern one that recieves updates regularly 
Running install.js file where the new lib is used and going though the prompts.
> FIO-10083: Replaces prompt library with inquirer

- src/db/index.js
- src/db/updates/2.4.2.js
https://formio.atlassian.net/browse/FIO-9099
For some reason, my changes in #1806 got reverted - this adds them back.
n/a
n/a
tests pass in formio and formio-server
> Fio 9099 4.4.x: fix startup errors

- src/util/util.js
This change simply ensures that we force the case of the parameters to ensure deterministic behavior of the api server when identifying the resources that are being utilized.
> Ensure the case is consistent for the url parameters.

- docker-compose.yml
> fxi typo in docker compose env variables for mongodb

- test/helper.js
This reverts commit 9b6a2365f70b91b70dae2088447c803ef6c2a7b2.
https://formio.atlassian.net/browse/FIO-8115
> Revert "FIO-8115: Fix project creation failed in tests because of missing 'project' type"

- src/util/email/renderEmail.js
- test/actions.js
- test/fixtures/forms/selectBoxesSourceTypeForm.js
https://formio.atlassian.net/browse/FIO-10226
**Component.values**  for Select Boxes component with for "data source = url"  is empty (it was empty before Brendan's big refactoring too). And I added the same logic ( where we get  values to render from submission) as it worked before Brendan's big refactoring  
n/a
n/a
I added unit test
> Fix-10226: data from select boxes not displaying

- src/util/email/renderEmail.js
- src/util/email/utils.js
https://formio.atlassian.net/browse/FIO-10231
convert the select component value to a string if it is an object so that it displays correctly in the email.
manually
> FIO-10231: fixed an issue where select value (object type)  is rendered as object Object in email

- src/db/install.js
https://formio.atlassian.net/browse/FIO-10197
Added indexes ({priority: 1, title: 1}) to actions collection to ensure support for sorting on in CosmosDB.
-
https://github.com/formio/formio-server/pull/1706
manually
> FIO-10043: adding composite indexes (for CosmosDB)

- package.json
- test/submission.js
- yarn.lock
https://formio.atlassian.net/browse/FIO-9984
updated core to new version with the default values fix and revert a previously changed test to its original state
https://github.com/formio/core/pull/268
tests
> FIO-9984: updated core and revert the test to its previous state

- src/db/updates/3.3.20.js
https://formio.atlassian.net/browse/FIO-10264
Added list of reserved names for projects.
-
https://github.com/formio/formio-monorepo/pull/197
manually
autotests
> FIO-10264: add reserved project name to config

- config/default.json
https://formio.atlassian.net/browse/FIO-10264
Added list of reserved names for projects.
n/a
n/a
@Maria-Golomb added tests upstream
> FIO-10264: add reserved project names to config

- src/util/email/utils.js
- test/export/CSVExporter/CSVExporter.js
- test/submission-access.js
Due to errors in the synchronization script, there has been some drift between the monorepo and the oss repos.  These are files that were changed in the monorepo, but not correctly changed in the standalone repo.
> syncing files from monorepo

- src/templates/import.js
- test/submission.js
https://formio.atlassian.net/browse/FIO-10271
The form revisions have [ 'administrator', 'authenticated', 'anonymous' ] as roles. These roles do not make it to a fallback function and need to be handled beforehand as you cant save roles [ 'administrator', 'authenticated', 'anonymous' ] to a database (they need to be object ids). Updated the roleMachineNameToId function to handle this case were a fallback function is not given. Also made some readability changes
N/A
https://github.com/formio/formio-server/pull/1713
N/A
Manually tested
> FIO-10271: fixed import 400 and 500 errors
